// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateCollection(arg1, arg2) {
  return window['go']['main']['App']['CreateCollection'](arg1, arg2);
}

export function GetCollections() {
  return window['go']['main']['App']['GetCollections']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function MakeRequest(arg1) {
  return window['go']['main']['App']['MakeRequest'](arg1);
}
