// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CreateCollection(arg1:string,arg2:string):Promise<void>;

export function GetCollections():Promise<Array<main.Collection>>;

export function Greet(arg1:string):Promise<string>;

export function MakeRequest(arg1:main.RequestParams):Promise<{[key: string]: any}>;
