// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Greet(arg1:string):Promise<string>;

export function MakeRequest(arg1:string,arg2:string,arg3:{[key: string]: string},arg4:string,arg5:{[key: string]: string},arg6:string):Promise<{[key: string]: any}>;
